[build-system]
requires = ["setuptools>=64.0"]
build-backend = "setuptools.build_meta"

[project]
name = "plu"
version = "0.1"
description = "Your project description"

[tool.setuptools]
packages = ["src"]