grenoble:
  # documents_generaux:
  #   - dispositions_generales
  #   - ppri
  #   - carnet_de_paysage
  # zones_a_urbaniser:
  #   - zone_AU
  #   - zone_AUC1
  #   - zone_AUC2
  #   - zone_AUC3
  #   - zone_AUCRU10
  #   - zone_AUD1
  #   - zone_AUD2
  #   - zone_AUD3
  #   - zone_AUD4
  #   - zone_AUE1
  #   - zone_AUP1r
  # zones_agricoles_et_naturelles:
  #   - zone_A
  #   - zone_AL
  #   - zone_N
  #   - zone_NL
  # zones_dediees:
  #   - zone_UE1
  #   - zone_UE2
  #   - zone_UE3
  #   - zone_UE4
  #   - zone_UV
  #   - zone_UZ1
  #   - zone_UZ2
  #   - zone_UZ3
  #   - zone_UZ4
  zones_urbaines_mixtes:
    - zone_UA1
    - zone_UA2
    - zone_UA3
    - zone_UB
    - zone_UC1
    - zone_UC2
    - zone_UC3
    - zone_UCRU1
    - zone_UCRU2
    - zone_UCRU3
    - zone_UCRU4
    - zone_UCRU5
    - zone_UCRU6
    - zone_UCRU7
    - zone_UCRU8
    - zone_UCRU9
    - zone_UCRU11
    - zone_UD1
    - zone_UD2
    - zone_UD3
    - zone_UD4